"""empty message

Revision ID: 3106b8fac08a
Revises: a04c401c9fbd
Create Date: 2025-10-22 00:14:08.560682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3106b8fac08a'
down_revision: Union[str, Sequence[str], None] = 'a04c401c9fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
